### ISSUE TITLE
Have a production server hosted on AWS

### ISSUE THREAD

**Issue by marilynzhang** [cs210/PYCK#29]
- buy a domain
- transfer database from sqlite3 to mysql!

**Comment by marilynzhang** [comment]
actually, don't need to transfer to mysql -- look into postgresql instead, which is actually also supported by Django!

**Comment by aszeng** [comment]
Didn't buy a domain, didn't transfer database to mysql

But domain hosted using elastic beanstalk, currently still using sqlite3 for now
