### ISSUE TITLE
Improve Reducer Architecture

### ISSUE THREAD

**Issue by FosterBirnbaum** [cs210/PYCK#31]
We currently have a single question.js reducer that handles all state changes. We should consider breaking this up to match the different components that we have.

**Comment by aszeng** [comment]
@FosterBirnbaum I'm classifying our old issues rn - would you classify this as Nice To Have or keep its current tag as part of the last sprint (i.e. necessary for future frontend dev work)?

**Comment by aszeng** [comment]
"Wow, that's super old... yeah, that's been done!"
